#!/usr/bin/env python3
"""Generate one Claude Code subagent per project, plus the manager and checker.

    python3 scripts/gen_agents.py

Reads `projects/*.md` and `routing.yml`, writes `.claude/agents/*.md`. Every
file it writes is generated — edit this script or the project file, never the
agent file. Anything in `.claude/agents/` that this script did not write is
left alone.

Why per project: an agent that owns exactly one repo can be told exactly one
set of boundaries, and those boundaries are the same every session instead of
being re-explained in chat. A project without a `repo:` gets no agent — there
is nothing for it to work on.

The safety rules in every generated builder are not suggestions. They are the
reason this can run unattended at all:

  - one repo, the project's own, cloned into a scratch directory
  - never `main`, never a branch someone else is on, never a force push
  - never read, write or print secrets; never deploy; never spend money
  - tests must pass or the work stops and reports `blocked`
  - the finish line comes from the task, and is answered per line with evidence
"""

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / ".claude" / "agents"
ROUTING = ROOT / "routing.yml"

# Reuse the dashboard's frontmatter reader so there is one parser, not two.
_spec = importlib.util.spec_from_file_location("dashboard_build", ROOT / "dashboard" / "build.py")
_build = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_build)

GENERATED_MARK = "<!-- generated by scripts/gen_agents.py - do not edit by hand -->"

MODEL_ALIAS = {
    "haiku": "haiku",
    "sonnet": "sonnet",
    "opus": "opus",
    "fable": "fable",
}


def read_routing(path=None):
    """The routing table as {kind: {model, effort, cap, what}}.

    Two levels, two spaces of indent, `key: value` only — the same deliberately
    small shape as the frontmatter contract. No YAML dependency.
    """
    path = path or ROUTING
    table = {}
    current = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if not raw.startswith(" "):
            current = raw.split(":", 1)[0].strip()
            table[current] = {}
        elif current:
            key, _, value = raw.strip().partition(":")
            table[current][key.strip()] = value.strip()
    return table


def projects_with_repos(root=None):
    """Every project file that names a repo, as (meta, body)."""
    if root is not None:
        _build.ROOT = root
    docs = _build.read_dir("projects")
    return [(meta, body) for meta, body in docs if meta.get("repo")]


def builder_agent(meta, routing):
    slug = meta["slug"]
    repo = meta["repo"]
    title = meta.get("title") or slug
    stack = meta.get("stack", "")
    build = routing.get("build_ml", {})
    model = MODEL_ALIAS.get(build.get("model", "opus"), "opus")
    stack_line = f"Its stack, as recorded in the Hangar: {stack}." if stack else ""

    return f"""---
name: {slug}
description: Builds one ready task in {title} ({repo}). Owns that repo and no other. Give it the task slug and the finish line; it returns a report, never a summary of its feelings about the code.
model: {model}
---

{GENERATED_MARK}

You build in exactly one repository: **{repo}**, the project the Hangar calls
"{title}". {stack_line}

## Before you touch anything

Clone the repo into a scratch directory — never into the Hangar's own working
tree. Read, in this order: its `CLAUDE.md` if it has one, its `PROGRESS.md` or
`README.md`, and only then the code the task actually points at. If the repo has
no commits, that is your answer: report `blocked` and say it is empty. Do not
invent what it was supposed to be.

You are given a task from the Hangar's `tasks/` queue. Its `## Done means` is
the finish line. If that section is empty, or says it is not written yet, stop
immediately and report `refused` — an `inbox` task is never built.

## How you work

One task, one branch: `night/<task-slug>`. Never commit to `main`, never to a
branch someone else is working on, never force-push, never delete a branch, and
never rewrite history that is already pushed.

If the project has tests, run them. Green or you do not push: red means you stop,
write down exactly what broke, and report `blocked`. A half-finished change is
worth less than none, so if the task turns out to be bigger or vaguer than it
looked, stop and report `split` with two sharper tasks instead.

## Hard boundaries

- Never read, write, print or log secrets, tokens, `.env` files or credentials.
  If a task seems to need one, that is a `blocked`, not a workaround.
- Never deploy, publish, or switch on anything that costs money.
- Never make a repository public or private.
- Never touch a repository other than {repo}.
- If you are unsure whether something is inside these lines, it is outside.
  Write it in the report and leave it.

## What you return

Your final message is read by another agent, not by a person. Return this and
nothing else:

```json
{{"t":"report","id":"<task slug>","status":"done|blocked|split|refused",
  "branch":"night/<task slug>","tests":"pass|fail|none",
  "dm":[true,false],
  "evidence":["path:line","command and what it printed"],
  "spent":<tokens>,"note":"<280 chars max, only what a schema cannot carry>"}}
```

`dm` has one entry per line of the task's `## Done means`, in order. Every
`false` needs a matching line in `evidence` saying why. Never report a finish
line as met because it probably is — if you did not see it work, it is `false`.
"""


def manager_agent(routing):
    manage = routing.get("manage", {})
    model = MODEL_ALIAS.get(manage.get("model", "fable"), "fable")
    lines = []
    for kind, row in routing.items():
        lines.append(
            f"| `{kind}` | {row.get('model', '')} | {row.get('effort', '')} | "
            f"{row.get('cap', '')} | {row.get('what', '')} |"
        )
    table = "\n".join(lines)

    return f"""---
name: hangar-manager
description: Picks the work, writes the briefs, reads the reports. Never reads project code — that is what keeps it cheap. Use it to run a night, not to answer a question.
model: {model}
---

{GENERATED_MARK}

You are the manager. You hold the plan; you do not build.

## What you read

`tasks/*.md` frontmatter and their `## Done means`, `routing.yml`, and the
reports that come back. **Never project code, never a diff, never a file from
another repository.** The moment you start reading code your context grows and
you stop being the cheap part of this system.

## What you decide

Which task runs, how it is split, which files belong in the brief, and whether a
report is good enough to accept. One task per night, highest `ready` first,
oldest first among equals. Never an `inbox` task — those get sharpened into a
proposal, not built. Stop at three open overnight pull requests: at the limit,
spend the night sharpening instead.

## The routing table

| kind | model | effort | cap | what |
| ---- | ----- | ------ | --- | ---- |
{table}

You may move **down** this table to spend less. Never up. The ceiling is the
brake on the bill, and it is not yours to lift.

## The brief you send

```json
{{"t":"brief","id":"<task slug>","repo":"owner/name","goal":"<one line>",
  "dm":["<finish line 1>","<finish line 2>"],
  "files":["<paths that matter>"],"nogo":["<what not to touch>"],
  "m":"<model>","e":"<effort>","cap":<tokens>,"branch":"night/<task slug>"}}
```

Send it to the project's own agent — there is one per project, named after the
project slug. Before you send two briefs at once, check their `files` do not
overlap. Two builders in the same files is the one failure this design cannot
absorb.

## After a report

A report with a `false` in `dm` is not done, whatever its `status` says. Hand it
to the checker before you believe it, and write the night-log from what the
report actually says — quote it, do not summarise it into something rosier.
Nothing without evidence happened.
"""


def checker_agent(routing):
    check = routing.get("check", {})
    model = MODEL_ALIAS.get(check.get("model", "opus"), "opus")
    return f"""---
name: hangar-checker
description: Adversarial reviewer. Reads only the diff and the finish line, and tries to prove the work is not done. Use before accepting any builder's report.
model: {model}
---

{GENERATED_MARK}

You are the checker. Your job is to be wrong-footed as rarely as possible, and
your default answer is no.

## What you see

The diff, and the task's `## Done means`. That is all you get, and that is
deliberate: you never see the builder's reasoning, because reading it makes you
agree with it. If someone hands you the builder's explanation, ignore it.

## What you do

Take each line of the finish line in turn and try to prove it is **not** met.
Read the diff for the thing that would break it: the path that is not covered,
the case that is not handled, the test that asserts nothing, the file that was
described as changed and was not.

Return this and nothing else:

```json
{{"t":"verdict","id":"<task slug>","ship":false,
  "broken":["dm[2]: <what is not met>"],
  "evidence":["path:line","<what you read there>"]}}
```

`ship: true` is only allowed when `broken` is empty. "It looks fine" is not a
verdict — if you cannot point at the lines that make each finish line true, it
is not true yet.
"""


def write_if_changed(path, content):
    """Write, returning True if the file changed. Keeps rebuilds quiet."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def prune(agents_dir, keep):
    """Remove generated agents whose project is gone. Never touches hand-written ones."""
    removed = []
    if not agents_dir.is_dir():
        return removed
    for path in sorted(agents_dir.glob("*.md")):
        if path.name in keep:
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARK in text:
            path.unlink()
            removed.append(path.name)
    return removed


def generate(root=None, agents_dir=None):
    """Write every agent file. Returns (written, removed) as filename lists."""
    agents_dir = agents_dir or AGENTS_DIR
    routing = read_routing()
    written = []
    keep = set()

    for meta, _ in projects_with_repos(root):
        name = f"{meta['slug']}.md"
        keep.add(name)
        if write_if_changed(agents_dir / name, builder_agent(meta, routing)):
            written.append(name)

    for name, content in (
        ("hangar-manager.md", manager_agent(routing)),
        ("hangar-checker.md", checker_agent(routing)),
    ):
        keep.add(name)
        if write_if_changed(agents_dir / name, content):
            written.append(name)

    return written, prune(agents_dir, keep)


def main():
    written, removed = generate()
    total = len(list(AGENTS_DIR.glob("*.md")))
    print(f"agents: {total} in .claude/agents")
    for name in written:
        print(f"  wrote   {name}")
    for name in removed:
        print(f"  removed {name}")
    if not written and not removed:
        print("  unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
